insert into skill(skill_id, name, level_cap) values
    (1, 'Communication', 5),
    (2, 'Imagination', 5),
    (3, 'Movement', 5),
    (4, 'Thinking', 5),
    (5, 'Potty', 3),
    (6, 'Social', 10),
    (7, 'Creativity', 10),
    (8, 'Motor', 10),
    (9, 'Mental', 10),
    (10, 'Charisma', 10),
    (11, 'Comedy', 10),
    (12, 'Cooking', 10),
    (13, 'Fishing', 10),
    (14, 'Fitness', 10),
    (15, 'Gardening', 10),
    (16, 'Gourmet cooking', 10),
    (17, 'Guitar', 10),
    (18, 'Handiness', 10),
    (19, 'Logic', 10),
    (20, 'Mischief', 10),
    (21, 'Mixology', 10),
    (22, 'Painting', 10),
    (23, 'Photography', 5),
    (24, 'Piano', 10),
    (25, 'Programming', 10),
    (26, 'Rocket science', 10),
    (27, 'Video gaming', 10),
    (28, 'Violin', 10),
    (29, 'Writing', 10),
    (30, 'Herbalism', 10),
    (31, 'Baking', 10),
    (32, 'Wellness', 10),
    (33, 'Dancing', 5),
    (34, 'DJ mixing', 10),
    (35, 'Singing', 10),
    (36, 'Pipe organ', 10),
    (37, 'Vampire lore', 15),
    (38, 'Bowling', 5),
    (39, 'Parenting', 10),
    (41, 'Veterinarian', 10),
    (42, 'Pet training', 5),
    (43, 'Archaeology', 10),
    (44, 'Selvadoradian culture', 5),
    (45, 'Flower arranging', 10),
    (46, 'Acting', 10),
    (47, 'Media production', 5),
    (48, 'Research & Debate', 10),
    (49, 'Robotics', 10),
    (50, 'Fabrication', 10),
    (51, 'Juice Fizzing', 5),
    (52, 'Knitting', 10),
    (53, 'Rock climbing', 10),
    (54, 'Skiing', 10),
    (55, 'Snowboarding', 10),
    (56, 'Medium', 5),
    (57, 'Cross-stitch', 5),
    (58, 'Entrepreneur', 5),
    (59, 'Horse riding', 10),
    (60, 'Nectar making', 10),
    (61, 'Gemology', 10),
    (62, 'Romance', 10),
    (63, 'Thanatology', 5),
    (64, 'Pottery', 10),
    (65, 'Tattooing', 10),
    (66, 'Apothecary', 10),
    (67, 'Natural living', 10),
    (68, 'Archery', 5),
    (69, 'Diving', 5),
    (70, 'Entomology', 5),
    (71, 'Papercraft', 10),
    (72, 'Swordsmanship', 10);

insert into trait(trait_id, name) values
    (1, 'Ambitious'),
    (2, 'Cheerful'),
    (3, 'Childish'),
    (4, 'Clumsy'),
    (5, 'Creative'),
    (6, 'Erratic'),
    (7, 'Genius'),
    (8, 'Gloomy'),
    (9, 'Goofball'),
    (10, 'High maintenance'),
    (11, 'Hot-headed'),
    (12, 'Lovebug'),
    (13, 'Paranoid'),
    (14, 'Practice makes perfect'),
    (15, 'Romantic'),
    (16, 'Romantically reserved'),
    (17, 'Self-assured'),
    (18, 'Squeamish'),
    (19, 'Unflirty'),
    (20, 'Wise'),
    (21, 'Art lover'),
    (22, 'Bookworm'),
    (23, 'Dance machine'),
    (24, 'Foodie'),
    (25, 'Geek'),
    (26, 'Loves outdoors'),
    (27, 'Maker'),
    (28, 'Music lover'),
    (29, 'Recycle disciple'),
    (30, 'Active'),
    (31, 'Active imagination'),
    (32, 'Adventurous'),
    (33, 'Chased by Death'),
    (34, 'Child of the island'),
    (35, 'Child of the ocean'),
    (36, 'Child of the village'),
    (37, 'Competitive'),
    (38, 'Disruptive'),
    (39, 'Freegan'),
    (40, 'Glutton'),
    (41, 'Green fiend'),
    (42, 'Kleptomaniac'),
    (43, 'Lactose intolerant'),
    (44, 'Lazy'),
    (45, 'Macabre'),
    (46, 'Materialistic'),
    (47, 'Mystical'),
    (48, 'Neat'),
    (49, 'Overachiever'),
    (50, 'Perfectionist'),
    (51, 'Rancher'),
    (52, 'Skeptical'),
    (53, 'Slob'),
    (54, 'Vegetarian'),
    (55, 'Animal enthusiast'),
    (56, 'Bro'),
    (57, 'Cat lover'),
    (58, 'Cringe'),
    (59, 'Dog lover'),
    (60, 'Evil'),
    (61, 'Family-oriented'),
    (62, 'Generous'),
    (63, 'Good'),
    (64, 'Grouch'),
    (65, 'Hates children'),
    (66, 'Horse lover'),
    (67, 'Idealist'),
    (68, 'Insider'),
    (69, 'Jealous'),
    (70, 'Loner'),
    (71, 'Loyal'),
    (72, 'Mean'),
    (73, 'Noncommittal'),
    (74, 'Nosy'),
    (75, 'Outgoing'),
    (76, 'Party animal'),
    (77, 'Plant lover'),
    (78, 'Proper'),
    (79, 'Self-absorbed'),
    (80, 'Shady'),
    (81, 'Snob'),
    (82, 'Socially awkward'),
    (83, 'Angelic'),
    (84, 'Charmer'),
    (85, 'Clingy'),
    (86, 'Fussy'),
    (87, 'Independent'),
    (88, 'Inquisitive'),
    (89, 'Silly'),
    (90, 'Wild'),
    (91, 'Cautious'),
    (92, 'Sensitive'),
    (93, 'Calm'),
    (94, 'Intense'),
    (95, 'Wiggly'),
    (96, 'Sunny');

insert into family_role(family_role_id, name) values
    (1, 'Head'),
    (2, 'Heir'),
    (3, 'Member');

insert into career(career_id, name, career_type) values
    (1, 'Astronaut', 'FULL_TIME'),
    (2, 'Athlete', 'FULL_TIME'),
    (3, 'Babysitter', 'PART_TIME'),
    (4, 'Barista', 'PART_TIME'),
    (5, 'Business', 'FULL_TIME'),
    (6, 'Criminal', 'FULL_TIME'),
    (7, 'Culinary', 'FULL_TIME'),
    (8, 'Entertainer', 'FULL_TIME'),
    (9, 'Fast food employee', 'PART_TIME'),
    (10, 'Freelance artist', 'FREELANCE'),
    (11, 'Freelance programmer', 'FREELANCE'),
    (12, 'Freelance writer', 'FREELANCE'),
    (13, 'Manual laborer', 'PART_TIME'),
    (14, 'Painter', 'FULL_TIME'),
    (15, 'Retail employee', 'PART_TIME'),
    (16, 'Secret agent', 'FULL_TIME'),
    (17, 'Style influencer', 'FULL_TIME'),
    (18, 'Tech guru', 'FULL_TIME'),
    (19, 'Writer', 'FULL_TIME'),
    (20, 'Detective', 'FULL_TIME'),
    (21, 'Doctor', 'FULL_TIME'),
    (22, 'Scientist', 'FULL_TIME'),
    (23, 'Critic', 'FULL_TIME'),
    (24, 'Politician', 'FULL_TIME'),
    (25, 'Social media', 'FULL_TIME'),
    (26, 'Gardener', 'FULL_TIME'),
    (27, 'Actor', 'FULL_TIME'),
    (28, 'Military', 'FULL_TIME'),
    (29, 'Conservationist', 'FULL_TIME'),
    (30, 'Diver', 'PART_TIME'),
    (31, 'Fisherman', 'PART_TIME'),
    (32, 'Freelance fashion photographer', 'FREELANCE'),
    (33, 'Education', 'FULL_TIME'),
    (34, 'Engineer', 'FULL_TIME'),
    (35, 'Law', 'FULL_TIME'),
    (36, 'Civil designer', 'FULL_TIME'),
    (37, 'Freelance crafter', 'FREELANCE'),
    (38, 'Salaryperson', 'FULL_TIME'),
    (39, 'Paranormal investigator', 'FREELANCE'),
    (40, 'Interior decorator', 'FULL_TIME'),
    (41, 'Simfluencer', 'PART_TIME'),
    (42, 'Video game streamer', 'PART_TIME'),
    (43, 'Handyperson', 'PART_TIME'),
    (44, 'Romance consultant', 'FULL_TIME'),
    (45, 'Reaper', 'FULL_TIME'),
    (46, 'Undertaker', 'FULL_TIME'),
    (47, 'Naturopath', 'FULL_TIME'),
    (48, 'Park worker', 'FULL_TIME'),
    (49, 'Noble', 'FULL_TIME');

insert into career_branch(career_branch_id, name, career_id) values
    (1, 'Space ranger', 1),
    (2, 'Interstellar smuggler', 1),
    (3, 'Professional athlete', 2),
    (4, 'Bodybuilder', 2),
    (5, 'Babysitter', 3),
    (6, 'Barista', 4),
    (7, 'Management', 5),
    (8, 'Investor', 5),
    (9, 'Boss', 6),
    (10, 'Oracle', 6),
    (11, 'Chef', 7),
    (12, 'Mixologist', 7),
    (13, 'Musician', 8),
    (14, 'Comedian', 8),
    (15, 'Fast food employee', 9),
    (16, 'Freelance artist', 10),
    (17, 'Freelance programmer', 11),
    (18, 'Freelance writer', 12),
    (19, 'Manual laborer', 13),
    (20, 'Master of the real', 14),
    (21, 'Patron of the arts', 14),
    (22, 'Retail employee', 15),
    (23, 'Diamond agent', 16),
    (24, 'Villain', 16),
    (25, 'Stylist', 17),
    (26, 'Trend setter', 17),
    (27, 'eSport gamer', 18),
    (28, 'Start-up entrepreneur', 18),
    (29, 'Author', 19),
    (30, 'Journalist', 19),
    (31, 'Detective', 20),
    (32, 'Doctor', 21),
    (33, 'Scientist', 22),
    (34, 'Arts critic', 23),
    (35, 'Food critic', 23),
    (36, 'Politician', 24),
    (37, 'Charity organizer', 24),
    (38, 'Internet personality', 25),
    (39, 'Public relations', 25),
    (40, 'Botanist', 26),
    (41, 'Floral designer', 26),
    (42, 'Actor', 27),
    (43, 'Covert operator', 28),
    (44, 'Officer', 28),
    (45, 'Environmental manager', 29),
    (46, 'Marine biologist', 29),
    (47, 'Diver', 30),
    (48, 'Fisherman', 31),
    (49, 'Freelance fashion photographer', 32),
    (50, 'Administrator', 33),
    (51, 'Professor', 33),
    (52, 'Computer engineer', 34),
    (53, 'Mechanical engineer', 34),
    (54, 'Judge', 35),
    (55, 'Private attorney', 35),
    (56, 'Civic planner', 36),
    (57, 'Green technician', 36),
    (58, 'Freelance crafter', 37),
    (59, 'Expert', 38),
    (60, 'Supervisor', 38),
    (61, 'Paranormal investigator', 39),
    (62, 'Interior decorator', 40),
    (63, 'Simfluencer', 41),
    (64, 'Video game streamer', 42),
    (65, 'Handyperson', 43),
    (66, 'Matchmaker', 44),
    (67, 'Relationship counselor', 44),
    (68, 'Reaper', 45),
    (69, 'Funeral director', 46),
    (70, 'Mortician', 46),
    (71, 'Apothe-curist', 47),
    (72, 'Lifestyle coaching', 47),
    (73, 'Park counselor', 48),
    (74, 'Park ranger', 48),
    (75, 'Noble', 49);


